/***************************************************************************
 # Copyright (c) 2015-23, NVIDIA CORPORATION. All rights reserved.
 # Copyright 2024 The Khronos Group, Inc.
 **************************************************************************/

/**
 * Attribute for tagging resources that should be bound to a root descriptor.
 */
[__AttributeUsage(_AttributeTargets.Var)]
struct rootAttribute
{};
